from __future__ import annotations

from lc.envs.scenarios.configs import ControlScenarioConfig, PlanningScenarioConfig


def _base_values(difficulty: str) -> dict[str, object]:
    table = {
        "easy": dict(num_uavs=1, num_obstacles=2, obstacle_layout="sparse", dynamic_obstacles=False, target_motion="static", world_scale=1.0, density=0.2),
        "medium": dict(num_uavs=3, num_obstacles=5, obstacle_layout="corridor", dynamic_obstacles=False, target_motion="linear", world_scale=1.5, density=0.35),
        "hard": dict(num_uavs=5, num_obstacles=8, obstacle_layout="dense", dynamic_obstacles=True, target_motion="curve", world_scale=2.0, density=0.55),
        "extreme": dict(num_uavs=8, num_obstacles=12, obstacle_layout="mixed", dynamic_obstacles=True, target_motion="evasive", world_scale=2.5, density=0.75),
    }
    if difficulty not in table:
        raise ValueError(f"Unsupported difficulty: {difficulty}")
    return table[difficulty]


def _rect(left: float, right: float, bottom: float, top: float) -> tuple[float, float, float, float]:
    return (left, right, bottom, top)


def _common_defaults() -> dict[str, object]:
    return {
        "target_distance_band": "random",
        "target_speed_scale": 0.0,
        "obstacle_speed_scale": 0.0,
        "target_margin": 0.18,
        "target_min_spawn_distance": 0.25,
        "target_max_spawn_distance": 0.8,
        "target_speed_threshold": 0.08,
        "workspace_safe_margin": 0.2,
        "obstacle_safe_buffer": 0.08,
        "path_feasibility_check": False,
        "target_clearance_radius": 0.5,
        "encircle_radius": 0.40,
        "encircle_radius_tol": 0.05,
        "encircle_angle_tol_deg": 15.0,
        "encircle_min_spacing": 0.20,
        "encircle_hold_seconds": 1.0,
    }


PLANNING_CURRICULUM_ENVS: dict[str, dict[str, object]] = {
    "guidance_G1": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 0,
        "stage_name": "guidance",
        "stage_label_zh": "到达学习",
        "curriculum_env": "guidance_G1",
        "num_uavs": 1,
        "num_obstacles": 0,
        "obstacle_layout": "none",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 0.75,
        "workspace_size_x": 1.5,
        "workspace_size_y": 1.5,
        "density": 0.0,
        "timeout_seconds": 60.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.05, 0.05, -0.05, 0.05),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "workspace_random",
        "target_region_bounds": _rect(-0.75, 0.75, -0.75, 0.75),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 1.0,
        "target_max_drift": 0.0,
        "target_max_spawn_distance": 0.5,
        "obstacle_count_range": (0, 0),
        "obstacle_size_small_range": (0, 0),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("none",),
    },
    "guidance_G2": {
        **_common_defaults(),
        "difficulty": "medium",
        "stage_index": 0,
        "stage_name": "guidance",
        "stage_label_zh": "到达学习",
        "curriculum_env": "guidance_G2",
        "num_uavs": 1,
        "num_obstacles": 0,
        "obstacle_layout": "none",
        "dynamic_obstacles": False,
        "target_motion": "drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": False,
        "world_scale": 0.75,
        "workspace_size_x": 1.5,
        "workspace_size_y": 1.5,
        "density": 0.0,
        "timeout_seconds": 60.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.05, 0.05, -0.05, 0.05),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "workspace_random",
        "target_region_bounds": _rect(-0.75, 0.75, -0.75, 0.75),
        "target_region_label_zh": "动态目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_speed_scale": 0.05,
        "target_max_drift": 0.30,
        "obstacle_count_range": (0, 0),
        "obstacle_size_small_range": (0, 0),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("none",),
    },
    "avoidance_A1": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障前期",
        "curriculum_env": "avoidance_A1",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 60.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.30,
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.4,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A1_gmix_softtimeout": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障前期混合软超时",
        "curriculum_env": "avoidance_A1_gmix_softtimeout",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 60.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.30,
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.4,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A1_skill_replay_timeout18": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "A1技能回放硬超时",
        "curriculum_env": "avoidance_A1_skill_replay_timeout18",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 18.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.30,
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.6,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A1_skill_replay_timeout25": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "A1技能回放25秒硬超时",
        "curriculum_env": "avoidance_A1_skill_replay_timeout25",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 25.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.30,
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.6,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A1_static_single": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "A1单静态障碍",
        "curriculum_env": "avoidance_A1_static_single",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 25.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.30,
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.6,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A2_static_multi": {
        **_common_defaults(),
        "difficulty": "medium",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "A2多静态障碍",
        "curriculum_env": "avoidance_A2_static_multi",
        "num_uavs": 1,
        "num_obstacles": 3,
        "obstacle_layout": "dual_side_block",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.38,
        "timeout_seconds": 30.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (2, 4),
        "obstacle_size_small_range": (2, 4),
        "obstacle_size_medium_range": (0, 1),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.30,
        "obstacle_layout_modes": ("path_center_offset", "dual_side_block", "cluster_block"),
    },
    "avoidance_A3_dynamic_few": {
        **_common_defaults(),
        "difficulty": "hard",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "A3少量动态障碍",
        "curriculum_env": "avoidance_A3_dynamic_few",
        "num_uavs": 1,
        "num_obstacles": 2,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": True,
        "target_motion": "small_drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": True,
        "target_speed_scale": 0.02,
        "obstacle_speed_scale": 0.025,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.42,
        "timeout_seconds": 30.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.55, 2.35, 1.15, 2.35),
        "target_region_label_zh": "小范围动态目标区域",
        "target_hold_radius": 0.12,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.18,
        "obstacle_count_range": (1, 2),
        "obstacle_size_small_range": (1, 2),
        "obstacle_size_medium_range": (0, 1),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.32,
        "obstacle_layout_modes": ("path_center_offset", "path_center_blocking", "dual_side_block"),
    },
    "avoidance_A4_dynamic_multi_target": {
        **_common_defaults(),
        "difficulty": "extreme",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "A4多障碍动态目标",
        "curriculum_env": "avoidance_A4_dynamic_multi_target",
        "num_uavs": 1,
        "num_obstacles": 4,
        "obstacle_layout": "cluster_block",
        "dynamic_obstacles": True,
        "target_motion": "drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": True,
        "target_speed_scale": 0.04,
        "obstacle_speed_scale": 0.035,
        "world_scale": 1.0,
        "workspace_size_x": 5.5,
        "workspace_size_y": 5.5,
        "density": 0.52,
        "timeout_seconds": 35.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.38, 0.38, -0.38, 0.38),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.55, 2.55, 1.10, 2.55),
        "target_region_label_zh": "较大动态目标区域",
        "target_hold_radius": 0.12,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.32,
        "obstacle_count_range": (3, 4),
        "obstacle_size_small_range": (2, 4),
        "obstacle_size_medium_range": (0, 2),
        "obstacle_size_large_range": (0, 0),
        "target_clearance_radius": 0.35,
        "obstacle_layout_modes": ("dual_side_block", "cluster_block", "path_center_offset"),
    },
    "avoidance_A1_gmix_softtimeout_free_motion": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障前期自由动作复现",
        "curriculum_env": "avoidance_A1_gmix_softtimeout_free_motion",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 60.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_min_spawn_distance": 2.1,
        "target_max_spawn_distance": 3.1,
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.4,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A1_gmix_softtimeout_soft_penalty": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障前期轻动作惩罚",
        "curriculum_env": "avoidance_A1_gmix_softtimeout_soft_penalty",
        "num_uavs": 1,
        "num_obstacles": 1,
        "obstacle_layout": "path_center_offset",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 5.0,
        "workspace_size_y": 5.0,
        "density": 0.25,
        "timeout_seconds": 60.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.32, 0.32, -0.32, 0.32),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(1.60, 2.35, 1.20, 2.35),
        "target_region_label_zh": "随机目标区域",
        "target_min_spawn_distance": 2.1,
        "target_max_spawn_distance": 3.1,
        "target_hold_radius": 0.10,
        "target_hold_seconds": 0.0,
        "target_max_drift": 0.0,
        "obstacle_count_range": (1, 1),
        "obstacle_size_small_range": (1, 1),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("path_center_offset_nonblocking", "path_center_blocking"),
        "a1_direct_block_ratio": 0.4,
        "a1_blocking_layout": "path_center_blocking",
        "a1_nonblocking_layout": "path_center_offset_nonblocking",
    },
    "avoidance_A2": {
        **_common_defaults(),
        "difficulty": "medium",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障中期",
        "curriculum_env": "avoidance_A2",
        "num_uavs": 1,
        "num_obstacles": 7,
        "obstacle_layout": "mid_left_block",
        "dynamic_obstacles": False,
        "target_motion": "small_drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 2.0,
        "workspace_size_y": 2.0,
        "density": 0.40,
        "timeout_seconds": 30.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.08, 0.08, -0.08, 0.08),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "workspace_random",
        "target_region_bounds": _rect(-1.0, 1.0, -1.0, 1.0),
        "target_region_label_zh": "扰动目标区域",
        "target_hold_radius": 0.12,
        "target_hold_seconds": 1.0,
        "target_speed_scale": 0.03,
        "target_max_drift": 0.15,
        "obstacle_count_range": (5, 7),
        "obstacle_size_small_range": (2, 4),
        "obstacle_size_medium_range": (3, 5),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("mid_left_block",),
    },
    "avoidance_A3": {
        **_common_defaults(),
        "difficulty": "hard",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障中期",
        "curriculum_env": "avoidance_A3",
        "num_uavs": 1,
        "num_obstacles": 7,
        "obstacle_layout": "multi_pattern",
        "dynamic_obstacles": False,
        "target_motion": "small_drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 2.0,
        "workspace_size_y": 2.0,
        "density": 0.45,
        "timeout_seconds": 30.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.08, 0.08, -0.08, 0.08),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "workspace_random",
        "target_region_bounds": _rect(-1.0, 1.0, -1.0, 1.0),
        "target_region_label_zh": "扰动目标区域",
        "target_hold_radius": 0.12,
        "target_hold_seconds": 1.0,
        "target_speed_scale": 0.03,
        "target_max_drift": 0.18,
        "obstacle_count_range": (5, 7),
        "obstacle_size_small_range": (2, 4),
        "obstacle_size_medium_range": (3, 5),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("mid_right_block", "dual_side_block", "cluster_block"),
    },
    "avoidance_A4": {
        **_common_defaults(),
        "difficulty": "extreme",
        "stage_index": 1,
        "stage_name": "avoidance",
        "stage_label_zh": "避障后期",
        "curriculum_env": "avoidance_A4",
        "num_uavs": 1,
        "num_obstacles": 10,
        "obstacle_layout": "wide_random",
        "dynamic_obstacles": False,
        "target_motion": "small_drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": False,
        "world_scale": 1.25,
        "workspace_size_x": 2.5,
        "workspace_size_y": 2.5,
        "density": 0.58,
        "timeout_seconds": 30.0,
        "success_mode": "hold_at_target",
        "spawn_mode": "origin_single",
        "spawn_region": _rect(-0.10, 0.10, -0.10, 0.10),
        "spawn_region_label_zh": "起始点附近",
        "spawn_min_separation": 0.0,
        "target_region_mode": "workspace_random",
        "target_region_bounds": _rect(-1.25, 1.25, -1.25, 1.25),
        "target_region_label_zh": "随机目标区域",
        "target_hold_radius": 0.10,
        "target_hold_seconds": 1.0,
        "target_speed_scale": 0.03,
        "target_max_drift": 0.16,
        "obstacle_count_range": (8, 10),
        "obstacle_size_small_range": (1, 4),
        "obstacle_size_medium_range": (3, 4),
        "obstacle_size_large_range": (2, 3),
        "obstacle_layout_modes": ("wide_random",),
        "path_feasibility_check": True,
    },
    "cooperation_C1": {
        **_common_defaults(),
        "difficulty": "easy",
        "stage_index": 2,
        "stage_name": "cooperation",
        "stage_label_zh": "C1双机协同接近静态目标",
        "curriculum_env": "cooperation_C1",
        "num_uavs": 2,
        "num_obstacles": 0,
        "obstacle_layout": "none",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.0,
        "workspace_size_x": 3.0,
        "workspace_size_y": 3.0,
        "density": 0.0,
        "timeout_seconds": 30.0,
        "success_mode": "cooperative_approach_target",
        "spawn_mode": "bottom_left_region_three_uavs",
        "spawn_region": _rect(-1.35, -0.45, -1.35, -0.45),
        "spawn_region_label_zh": "左下起始区域",
        "spawn_min_separation": 0.20,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(0.45, 1.35, 0.45, 1.35),
        "target_region_label_zh": "右上目标区域",
        "target_hold_radius": 0.18,
        "target_hold_seconds": 0.5,
        "target_max_drift": 0.0,
        "encircle_radius": 0.22,
        "encircle_min_spacing": 0.28,
        "obstacle_count_range": (0, 0),
        "obstacle_size_small_range": (0, 0),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("none",),
        "path_feasibility_check": False,
    },
    "cooperation_C2": {
        **_common_defaults(),
        "difficulty": "medium",
        "stage_index": 2,
        "stage_name": "cooperation",
        "stage_label_zh": "C2双机协同跟踪运动目标",
        "curriculum_env": "cooperation_C2",
        "num_uavs": 2,
        "num_obstacles": 0,
        "obstacle_layout": "none",
        "dynamic_obstacles": False,
        "target_motion": "drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": False,
        "target_speed_scale": 0.04,
        "world_scale": 1.0,
        "workspace_size_x": 3.0,
        "workspace_size_y": 3.0,
        "density": 0.0,
        "timeout_seconds": 35.0,
        "success_mode": "cooperative_approach_target",
        "spawn_mode": "bottom_left_region_three_uavs",
        "spawn_region": _rect(-1.35, -0.45, -1.35, -0.45),
        "spawn_region_label_zh": "左下起始区域",
        "spawn_min_separation": 0.20,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(0.35, 1.25, 0.35, 1.25),
        "target_region_label_zh": "右上动态目标区域",
        "target_hold_radius": 0.20,
        "target_hold_seconds": 0.5,
        "target_max_drift": 0.25,
        "encircle_radius": 0.24,
        "encircle_min_spacing": 0.30,
        "obstacle_count_range": (0, 0),
        "obstacle_size_small_range": (0, 0),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("none",),
        "path_feasibility_check": False,
    },
    "cooperation_C3": {
        **_common_defaults(),
        "difficulty": "hard",
        "stage_index": 2,
        "stage_name": "cooperation",
        "stage_label_zh": "C3三机基础环绕",
        "curriculum_env": "cooperation_C3",
        "num_uavs": 3,
        "num_obstacles": 0,
        "obstacle_layout": "none",
        "dynamic_obstacles": False,
        "target_motion": "static",
        "target_is_dynamic": False,
        "obstacle_is_dynamic": False,
        "world_scale": 1.1,
        "workspace_size_x": 3.2,
        "workspace_size_y": 3.2,
        "density": 0.0,
        "timeout_seconds": 40.0,
        "success_mode": "encircle_target",
        "spawn_mode": "bottom_left_region_three_uavs",
        "spawn_region": _rect(-1.45, -0.45, -1.45, -0.45),
        "spawn_region_label_zh": "左下起始区域",
        "spawn_min_separation": 0.20,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(0.35, 1.35, 0.35, 1.35),
        "target_region_label_zh": "右上目标区域",
        "target_hold_radius": 0.15,
        "target_hold_seconds": 0.5,
        "target_speed_scale": 0.0,
        "target_max_drift": 0.0,
        "encircle_radius": 0.36,
        "encircle_radius_tol": 0.08,
        "encircle_angle_tol_deg": 22.0,
        "encircle_min_spacing": 0.30,
        "encircle_hold_seconds": 0.5,
        "obstacle_count_range": (0, 0),
        "obstacle_size_small_range": (0, 0),
        "obstacle_size_medium_range": (0, 0),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("none",),
        "path_feasibility_check": False,
    },
    "cooperation_C4": {
        **_common_defaults(),
        "difficulty": "extreme",
        "stage_index": 2,
        "stage_name": "cooperation",
        "stage_label_zh": "C4障碍环境协同环绕",
        "curriculum_env": "cooperation_C4",
        "num_uavs": 3,
        "num_obstacles": 4,
        "obstacle_layout": "coop_random",
        "dynamic_obstacles": False,
        "target_motion": "drift",
        "target_is_dynamic": True,
        "obstacle_is_dynamic": False,
        "target_speed_scale": 0.035,
        "world_scale": 1.25,
        "workspace_size_x": 3.5,
        "workspace_size_y": 3.5,
        "density": 0.45,
        "timeout_seconds": 45.0,
        "success_mode": "encircle_target",
        "spawn_mode": "bottom_left_region_three_uavs",
        "spawn_region": _rect(-1.55, -0.45, -1.55, -0.45),
        "spawn_region_label_zh": "左下起始区域",
        "spawn_min_separation": 0.20,
        "target_region_mode": "upper_right_square",
        "target_region_bounds": _rect(0.35, 1.45, 0.35, 1.45),
        "target_region_label_zh": "右上动态目标区域",
        "target_hold_radius": 0.15,
        "target_hold_seconds": 0.5,
        "target_max_drift": 0.25,
        "target_clearance_radius": 0.35,
        "encircle_radius": 0.40,
        "encircle_radius_tol": 0.09,
        "encircle_angle_tol_deg": 24.0,
        "encircle_min_spacing": 0.32,
        "encircle_hold_seconds": 0.5,
        "obstacle_count_range": (2, 4),
        "obstacle_size_small_range": (2, 4),
        "obstacle_size_medium_range": (0, 1),
        "obstacle_size_large_range": (0, 0),
        "obstacle_layout_modes": ("coop_random", "cluster_block", "dual_side_block"),
        "path_feasibility_check": True,
    },
}


_LEGACY_PLANNING_BY_STAGE = {
    0: {"easy": "guidance_G1", "medium": "guidance_G2", "hard": "guidance_G2", "extreme": "guidance_G2"},
    1: {"easy": "avoidance_A1", "medium": "avoidance_A2", "hard": "avoidance_A3", "extreme": "avoidance_A4"},
    2: {"easy": "cooperation_C1", "medium": "cooperation_C2", "hard": "cooperation_C3", "extreme": "cooperation_C4"},
}


def build_control_scenario(difficulty: str) -> ControlScenarioConfig:
    base = _base_values(difficulty)
    disturbance = {"easy": 0.05, "medium": 0.1, "hard": 0.2, "extreme": 0.35}[difficulty]
    return ControlScenarioConfig(
        difficulty=difficulty,
        disturbance_level=disturbance,
        control_frequency_hz=100,
        rl_frequency_hz=10,
        **base,
    )


def build_planning_scenario(
    difficulty: str | None = None,
    stage_index: int = 0,
    curriculum_env: str | None = None,
) -> PlanningScenarioConfig:
    env_name = curriculum_env
    if env_name is None:
        difficulty_name = difficulty or "medium"
        env_name = _LEGACY_PLANNING_BY_STAGE[min(max(stage_index, 0), 2)][difficulty_name]
    if env_name not in PLANNING_CURRICULUM_ENVS:
        raise ValueError(f"Unsupported planning curriculum env: {env_name}")
    spec = dict(PLANNING_CURRICULUM_ENVS[env_name])
    obstacle_count_range = tuple(spec["obstacle_count_range"])
    num_uavs = int(spec["num_uavs"])
    spec.pop("curriculum_env", None)
    return PlanningScenarioConfig(
        curriculum_env=env_name,
        max_neighbors=2,
        max_obstacles=4,
        **spec,
    )
